/**
 * Build-time snapshots of all PUBLIC data, generated by
 * `scripts/prefetch-supabase.ts` (+ `fetch-github.ts`) during the build.
 *
 * The public site reads these instead of calling Supabase at runtime, so there
 * are no runtime data requests and no loading states. The admin keeps using the
 * live hooks in src/hooks/* to edit; a rebuild (via the admin Publish button)
 * regenerates these files.
 */
import contactInfoData from "./contact-info.json";
import languagesData from "./languages.json";
import processStepsData from "./process-steps.json";
import profileData from "./profile.json";
import projectsData from "./projects.json";
import testimonialsData from "./testimonials.json";

import type { Experience, Language, ProfileInfo } from "@/components/about/aboutData";
import type { ProcessStep } from "@/components/process/processIcons";
import type { ContactInfo } from "@/hooks/useContactInfo";
import type { Testimonial } from "@/hooks/useTestimonials";
import type { Project } from "@/components/work/projects";

const profileJson = profileData as {
  profile: ProfileInfo;
  experience: Experience[];
  skills: string[];
};

export const profile: ProfileInfo = profileJson.profile;
export const experience: Experience[] = profileJson.experience;
export const skills: string[] = profileJson.skills;
export const projects = projectsData as unknown as Project[];
export const processSteps = processStepsData as unknown as ProcessStep[];
export const testimonials = testimonialsData as unknown as Testimonial[];
export const contactInfo = contactInfoData as unknown as ContactInfo;
export const languages = languagesData as unknown as Language[];
